"""
Tool: save_markdown

Assembles the final Notion-ready markdown file from all the generated
content: summaries, images, and the references pie chart.
"""

import json
import shutil
from datetime import date
from pathlib import Path

from langchain_core.tools import tool


def _build_markdown(
    title: str,
    authors: str,
    published: str,
    doi: str,
    overview: str,
    contribution: str,
    state_of_the_art: str,
    methodology_overview: str,
    methodology_details: str,
    evaluation: str,
    key_results: str,
    references_summary: str,
    chart_filename: str,
    figures: list[dict],
) -> str:
    """
    Build the full markdown string following the agreed output template.

    Args:
        title: Paper title.
        authors: Comma-separated author list.
        published: Year and venue.
        doi: DOI or link (can be empty).
        overview: 3-5 sentence overview.
        contribution: 4-6 sentence contribution description.
        state_of_the_art: 1-2 paragraph related work summary.
        methodology_overview: High-level method description.
        methodology_details: Detailed method walkthrough with formulae.
        evaluation: Evaluation setup description.
        key_results: Bullet-point results.
        references_summary: Top venues text.
        chart_filename: Filename of the pie chart in the images folder.
        figures: List of dicts with "filename", "caption", "section" keys.
    """
    lines = []

    # Header
    lines.append(f"# Paper Summary: {title}")
    lines.append("")
    lines.append(f"**Authors:** {authors}")
    lines.append(f"**Published:** {published}")
    if doi:
        lines.append(f"**DOI/Link:** {doi}")
    lines.append("")
    lines.append("---")
    lines.append("")

    # Helper to insert figures for a given section (fuzzy matching)
    def insert_figures(section_keywords: list[str]):
        for fig in figures:
            fig_section = fig.get("section", "").lower()
            if any(kw in fig_section for kw in section_keywords):
                lines.append("")
                caption = fig.get("caption", "")
                # Use short alt-text, show full caption below
                alt_text = caption[:80] + "..." if len(caption) > 80 else caption
                lines.append(f"![{alt_text}](images/{fig['filename']})")
                if caption:
                    lines.append(f"*{caption}*")
                lines.append("")

    # Overview
    lines.append("## Overview")
    lines.append("")
    lines.append(overview)
    insert_figures(["overview"])
    lines.append("")

    # Contribution
    lines.append("## Contribution")
    lines.append("")
    lines.append(contribution)
    insert_figures(["contribution"])
    lines.append("")

    # State of the Art
    lines.append("## State of the Art")
    lines.append("")
    lines.append(state_of_the_art)
    insert_figures(["state of the art", "related", "background"])
    lines.append("")

    # Methodology
    lines.append("## Methodology")
    lines.append("")
    lines.append(methodology_overview)
    lines.append("")
    lines.append("### Method Details")
    lines.append("")
    lines.append(methodology_details)
    insert_figures(["method", "architecture", "model", "approach", "framework"])
    lines.append("")

    # Evaluation
    lines.append("## Evaluation")
    lines.append("")
    lines.append(evaluation)
    insert_figures(["eval", "experiment", "setup"])
    lines.append("")

    # Key Results
    lines.append("## Key Results")
    lines.append("")
    lines.append(key_results)
    insert_figures(["result", "performance", "comparison", "ablat"])
    lines.append("")

    # References Analysis
    lines.append("## References Analysis")
    lines.append("")
    if chart_filename:
        lines.append(f"![Reference Distribution by Venue](images/{chart_filename})")
        lines.append("")
    lines.append(references_summary)
    lines.append("")

    # Footer
    lines.append("---")
    lines.append(f"*Generated by Research Paper Copilot on {date.today().isoformat()}*")

    return "\n".join(lines)


def _save_output(
    markdown_content: str,
    output_dir: str,
    image_source_dir: str,
    chart_source_path: str,
    figure_filenames: list[str],
) -> str:
    """
    Save the markdown file and copy associated images to the output directory.

    Directory layout:
        output_dir/
        ├── summary.md
        └── images/
            ├── figure_01.png
            ├── figure_02.png
            └── references_piechart.png
    """
    out = Path(output_dir)
    images_dir = out / "images"
    images_dir.mkdir(parents=True, exist_ok=True)

    # Save markdown
    md_path = out / "summary.md"
    md_path.write_text(markdown_content, encoding="utf-8")

    # Copy figures
    src_dir = Path(image_source_dir)
    for fname in figure_filenames:
        src = src_dir / fname
        if src.exists():
            shutil.copy2(src, images_dir / fname)

    # Copy chart (skip if already in the target directory)
    if chart_source_path:
        chart_src = Path(chart_source_path).resolve()
        chart_dst = (images_dir / chart_src.name).resolve()
        if chart_src.exists() and chart_src != chart_dst:
            shutil.copy2(chart_src, chart_dst)

    return str(md_path)


@tool
def save_markdown(content_json: str) -> str:
    """Assemble and save the final markdown summary with images.

    Args:
        content_json: JSON string with all the content fields:
            - title, authors, published, doi
            - overview, contribution, state_of_the_art
            - methodology_overview, methodology_details
            - evaluation, key_results, references_summary
            - chart_source_path: path to the pie chart PNG
            - image_source_dir: directory containing extracted figures
            - output_dir: where to save the final output
            - figures: list of {filename, caption, section} dicts

    Returns:
        Path to the saved summary.md file.
    """
    data = json.loads(content_json)

    # Build figures list with defaults
    figures = data.get("figures", [])
    chart_source = data.get("chart_source_path", "")
    chart_filename = Path(chart_source).name if chart_source else ""

    md = _build_markdown(
        title=data.get("title", "Untitled"),
        authors=data.get("authors", "Unknown"),
        published=data.get("published", "Unknown"),
        doi=data.get("doi", ""),
        overview=data.get("overview", ""),
        contribution=data.get("contribution", ""),
        state_of_the_art=data.get("state_of_the_art", ""),
        methodology_overview=data.get("methodology_overview", ""),
        methodology_details=data.get("methodology_details", ""),
        evaluation=data.get("evaluation", ""),
        key_results=data.get("key_results", ""),
        references_summary=data.get("references_summary", ""),
        chart_filename=chart_filename,
        figures=figures,
    )

    figure_filenames = [f["filename"] for f in figures]

    saved_path = _save_output(
        markdown_content=md,
        output_dir=data.get("output_dir", "output"),
        image_source_dir=data.get("image_source_dir", ""),
        chart_source_path=chart_source,
        figure_filenames=figure_filenames,
    )

    return saved_path
